apiVersion: batch/v1
kind: Job
metadata:
  name: init-variables-on-redis
  namespace: init-variables-on-redis
  labels:
    app: init-variables-on-redis
spec:
  template:
    metadata:
      labels:
        app: init-variables-on-redis
    spec:
      restartPolicy: Never  # O job roda uma vez e não reinicia
      containers:
        - name: redis-init
          image: samirsauma/init-variables-on-redis:v6
          command: ["node", "/app/base.js"]  # Certifique-se de que o script existe no container
          env:
            - name: REDIS_NODES
              value: "redis-cluster-0.redis-cluster.redis-cluster.svc.cluster.local:6379,redis-cluster-1.redis-cluster.redis-cluster.svc.cluster.local:6379,redis-cluster-2.redis-cluster.redis-cluster.svc.cluster.local:6379"
            - name: NODE_ENV
              value: "production"
