apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: matching-engine-hpa
  namespace: matching-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matching-engine
  minReplicas: 10
  maxReplicas: 80
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Escala quando CPU atinge 70%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 65  # Escala quando Memória atinge 65%
