apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30092  # Porta externa para conectar ao Kafka
          brokers:
            - broker: 0
              nodePort: 30093
            - broker: 1
              nodePort: 30094
            - broker: 2
              nodePort: 30095
    storage:
      type: ephemeral
    # Parâmetros de configuração do Kafka para melhorar performance
    config:
      # Exemplo: aumente o número de threads de rede e de I/O conforme necessário
      num.network.threads: "3"
      num.io.threads: "8"
      # Aumenta o tamanho máximo das requisições (ajuste conforme o tamanho esperado das mensagens)
      socket.request.max.bytes: "104857600"
      # Outros parâmetros podem ser ajustados, como:
      # log.segment.bytes, log.retention.hours, etc.
    # Defina os recursos para os pods do Kafka
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
    config:
      server.1: "kafka-zookeeper-0.kafka-zookeeper-nodes.kafka.svc.cluster.local:2888:3888:participant"
      server.2: "kafka-zookeeper-1.kafka-zookeeper-nodes.kafka.svc.cluster.local:2888:3888:participant"
      server.3: "kafka-zookeeper-2.kafka-zookeeper-nodes.kafka.svc.cluster.local:2888:3888:participant"
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  entityOperator:
    topicOperator: {}
    userOperator: {}
