apiVersion: v1
kind: ConfigMap
metadata:
  name: sysctl-settings
data:
  sysctl.conf: |
    vm.swappiness=0
    net.core.somaxconn=65535
    fs.file-max=2097152
    net.ipv4.tcp_max_syn_backlog=65535
