apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "$(KAFKA_BROKER_ID_NUMBER)"
            - name: KAFKA_BROKER_ID_NUMBER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['pod.alpha.kubernetes.io/ordinal']
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.kafka.svc.cluster.local:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(POD_NAME).kafka.kafka.svc.cluster.local:9092
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
