apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: redis-cluster
  labels:
    app: redis
spec:
  serviceName: redis-cluster
  replicas: 6  # Exemplo: 3 mestres e 3 réplicas
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
      containers:
        - name: redis
          image: redis:7.0-alpine
          command:
            - "sh"
            - "-c"
            - |
              # Inicia o Redis em background
              redis-server /etc/redis/redis.conf &
              # Se for o primeiro pod, aguarda e cria o cluster
              if [ "$(hostname)" = "redis-cluster-0" ]; then
                echo "Inicializando cluster Redis..."
                sleep 10
                echo "yes" | redis-cli --cluster create \
                  redis-cluster-0.redis-cluster.redis-cluster.svc.cluster.local:6379 \
                  redis-cluster-1.redis-cluster.redis-cluster.svc.cluster.local:6379 \
                  redis-cluster-2.redis-cluster.redis-cluster.svc.cluster.local:6379 \
                  redis-cluster-3.redis-cluster.redis-cluster.svc.cluster.local:6379 \
                  redis-cluster-4.redis-cluster.redis-cluster.svc.cluster.local:6379 \
                  redis-cluster-5.redis-cluster.redis-cluster.svc.cluster.local:6379 \
                  --cluster-replicas 1
                sleep 5
              fi
              # Aguarda o processo do Redis (mantém o container ativo)
              wait
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis
              readOnly: true
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      # Montagem do ConfigMap (não necessita de PVC)
      volumes:
        - name: redis-config
          configMap:
            name: redis-cluster-config
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
