apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer
  namespace: order-consumer
spec:
  replicas: 3  # Pode escalar para processar múltiplas ordens
  selector:
    matchLabels:
      app: order-consumer
  template:
    metadata:
      labels:
        app: order-consumer
    spec:
      containers:
        - name: order-consumer
          image: order-consumer:latest  # Substituir pelo repositório real
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
